---

rest:
  hostname: localhost
  port: 12121
  token: "random-token-for-user-service"
  root: "user"
  endpoints:
    - path: /auth/credentials
      method: POST
    - path: /auth/platform
      method: POST
    - path: /auth/server
      method: POST
rpc:
  hostname: localhost
  port: 12122