---
log_level: trace
rest:
  hostname: ogbuser
  port: 12121
  token: "random-token-for-user"
  root: "user"
  endpoints:
    - path: /auth/credentials
      method: POST
      skip_auth_middleware: true
    - path: /auth/platform
      method: POST
      skip_auth_middleware: true
    - path: /auth/server
      method: POST
      skip_auth_middleware: true
    - path: /token
      method: POST
      skip_auth_middleware: false
rpc:
  hostname: ogbuser
  port: 12122
postgres:
  ssl_mode: false
  hostname: userdb
  port: 5432
  database: userdb
  username: userdbadmin
  password: userdbpassword
  max_open_cons: 32
  max_idle_cons: 32
  conn_max_lifetime: 1800
  source_file: db/db.sql
crypto:
  jwt:
    secret: "very-secure-string"
    issuer: "ogbuser"
    expiry: 1440
  argon:
    memory: 65536
    iterations: 3
    parallelism: 2
    salt_length: 16
    key_length: 32
kafka:
  brokers:
    - kafka:29092
  topic: "user"